language: rust
cache: cargo

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial
    - os: linux
      sudo: false
      dist: trusty
    - os: linux
      sudo: false
      dist: precise
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode9.0
    - os: osx
      osx_image: xcode10.0
    - os: windows

addons:
  apt:
    packages:
      - libc6-dev
      - libgtest-dev
      - cmake

before_script:
  - uname
  - env | sort

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
    fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

