language: rust
cache: cargo

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial
      rust: stable
    - os: linux
      sudo: false
      dist: xenial
      rust: beta
    - os: linux
      sudo: false
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
    - os: linux
      sudo: false
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libclang-6.0-dev
            - llvm-6.0-tools
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.1
    - os: windows

addons:
  apt:
    packages:
      - cmake

before_script:
  - uname
  - env | sort

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      csrutil status || true;
      brew update;
      brew upgrade cmake;
    fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

