[package]
name = "BuildEAR"
version = "3.1.0"
authors = ["László Nagy <rizsotto at gmail dot com>"]
license = "GPL-3.0-only"
description = "InterceptWrappers is a set of developer tool wrappers."
homepage = "https://github.com/rizsotto/Bear"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[[bin]]
name = "intercept"
path = "src/main.rs"

[dependencies]
intercept = { path = "./intercept" }

dirs = "1.0"
env_logger = "0.5.13"
error-chain = "0.12"
lazy_static = "1.2"
libc = "0.2"
log = "0.4"

[dependencies.clap]
version = "~2.32.0"
default-features = false

[workspace]
members = [
    "intercept",
    "intercept-preload",
    "intercept-wrappers"
]
