[package]
name = "bear"
version = "3.1.0"
authors = ["László Nagy <rizsotto at gmail dot com>"]
license = "GPL3"
description = "BuildEAR is a tool that generates a compilation database for clang tooling."

[[bin]]
name = "bear2"
path = "src/main.rs"

[lib]
name = "intercept"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]                                                                                            
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.5.13"
tempdir = "0.3.7"

[dependencies.clap]
version = "~2.32.0"
default-features = false
