[package]
name = "bear"
version = "3.1.0"
authors = ["László Nagy <rizsotto at gmail dot com>"]
license = "GPL3"
description = "BuildEAR is a tool that generates a compilation database for clang tooling."

[[bin]]
name = "bear2"
path = "src/main.rs"

[lib]
name = "intercept"
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]                                                                                            
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.3.8"
env_logger = "0.4.3"
tempdir = "0.3.5"
libc = "0.2"

[dependencies.clap]
version = "~2.26.0"
default-features = false
